# ExceptionHandlingContruct

The provided C++ code initializes variables x and y, attempts division by zero within a try block, throwing an integer exception if division by zero occurs, catching and handling the exception to print a message indicating division by zero and its code, and then continues to print "Bye" regardless of whether an exception was caught or not.
